//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaruCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaruCore.Resources.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to east.
        /// </summary>
        public static string DirectionEast {
            get {
                return ResourceManager.GetString("DirectionEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north.
        /// </summary>
        public static string DirectionNorth {
            get {
                return ResourceManager.GetString("DirectionNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to northeast.
        /// </summary>
        public static string DirectionNortheast {
            get {
                return ResourceManager.GetString("DirectionNortheast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to northwest.
        /// </summary>
        public static string DirectionNorthwest {
            get {
                return ResourceManager.GetString("DirectionNorthwest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south.
        /// </summary>
        public static string DirectionSouth {
            get {
                return ResourceManager.GetString("DirectionSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to southeast.
        /// </summary>
        public static string DirectionSoutheast {
            get {
                return ResourceManager.GetString("DirectionSoutheast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to southwest.
        /// </summary>
        public static string DirectionSouthwest {
            get {
                return ResourceManager.GetString("DirectionSouthwest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to west.
        /// </summary>
        public static string DirectionWest {
            get {
                return ResourceManager.GetString("DirectionWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour ago.
        /// </summary>
        public static string TimeHourAgo {
            get {
                return ResourceManager.GetString("TimeHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string TimeHoursAgo {
            get {
                return ResourceManager.GetString("TimeHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute ago.
        /// </summary>
        public static string TimeMinuteAgo {
            get {
                return ResourceManager.GetString("TimeMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string TimeMinutesAgo {
            get {
                return ResourceManager.GetString("TimeMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string TimeNow {
            get {
                return ResourceManager.GetString("TimeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string WeatherClear {
            get {
                return ResourceManager.GetString("WeatherClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dense freezing drizzle.
        /// </summary>
        public static string WeatherDenseFreezingDrizzle {
            get {
                return ResourceManager.GetString("WeatherDenseFreezingDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fog.
        /// </summary>
        public static string WeatherFog {
            get {
                return ResourceManager.GetString("WeatherFog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy drizzle.
        /// </summary>
        public static string WeatherHeavyDrizzle {
            get {
                return ResourceManager.GetString("WeatherHeavyDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy freezing rain.
        /// </summary>
        public static string WeatherHeavyFreezingRain {
            get {
                return ResourceManager.GetString("WeatherHeavyFreezingRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy hail.
        /// </summary>
        public static string WeatherHeavyHail {
            get {
                return ResourceManager.GetString("WeatherHeavyHail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy rain.
        /// </summary>
        public static string WeatherHeavyRain {
            get {
                return ResourceManager.GetString("WeatherHeavyRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy rain showers.
        /// </summary>
        public static string WeatherHeavyRainShowers {
            get {
                return ResourceManager.GetString("WeatherHeavyRainShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy snow.
        /// </summary>
        public static string WeatherHeavySnow {
            get {
                return ResourceManager.GetString("WeatherHeavySnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy snow showers.
        /// </summary>
        public static string WeatherHeavySnowShowers {
            get {
                return ResourceManager.GetString("WeatherHeavySnowShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light drizzle.
        /// </summary>
        public static string WeatherLightDrizzle {
            get {
                return ResourceManager.GetString("WeatherLightDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light freezing drizzle.
        /// </summary>
        public static string WeatherLightFreezingDrizzle {
            get {
                return ResourceManager.GetString("WeatherLightFreezingDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light freezing rain.
        /// </summary>
        public static string WeatherLightFreezingRain {
            get {
                return ResourceManager.GetString("WeatherLightFreezingRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light hail.
        /// </summary>
        public static string WeatherLightHail {
            get {
                return ResourceManager.GetString("WeatherLightHail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light rain.
        /// </summary>
        public static string WeatherLightRain {
            get {
                return ResourceManager.GetString("WeatherLightRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light rain showers.
        /// </summary>
        public static string WeatherLightRainShowers {
            get {
                return ResourceManager.GetString("WeatherLightRainShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light snow.
        /// </summary>
        public static string WeatherLightSnow {
            get {
                return ResourceManager.GetString("WeatherLightSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light snow showers.
        /// </summary>
        public static string WeatherLightSnowShowers {
            get {
                return ResourceManager.GetString("WeatherLightSnowShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate drizzle.
        /// </summary>
        public static string WeatherModerateDrizzle {
            get {
                return ResourceManager.GetString("WeatherModerateDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate rain.
        /// </summary>
        public static string WeatherModerateRain {
            get {
                return ResourceManager.GetString("WeatherModerateRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate rain showers.
        /// </summary>
        public static string WeatherModerateRainShowers {
            get {
                return ResourceManager.GetString("WeatherModerateRainShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate snow.
        /// </summary>
        public static string WeatherModerateSnow {
            get {
                return ResourceManager.GetString("WeatherModerateSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overcast.
        /// </summary>
        public static string WeatherOvercast {
            get {
                return ResourceManager.GetString("WeatherOvercast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partly cloudy.
        /// </summary>
        public static string WeatherPartlyCloudy {
            get {
                return ResourceManager.GetString("WeatherPartlyCloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snow grains.
        /// </summary>
        public static string WeatherSnowGrains {
            get {
                return ResourceManager.GetString("WeatherSnowGrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sunny.
        /// </summary>
        public static string WeatherSunny {
            get {
                return ResourceManager.GetString("WeatherSunny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thunderstorm.
        /// </summary>
        public static string WeatherThunderstorm {
            get {
                return ResourceManager.GetString("WeatherThunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string WeatherUnknown {
            get {
                return ResourceManager.GetString("WeatherUnknown", resourceCulture);
            }
        }
    }
}
