//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaruApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaruApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to fav..
        /// </summary>
        public static string AppBarAddToFavorites {
            get {
                return ResourceManager.GetString("AppBarAddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppBarCancel {
            get {
                return ResourceManager.GetString("AppBarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string AppBarFavorites {
            get {
                return ResourceManager.GetString("AppBarFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string AppBarPinToStart {
            get {
                return ResourceManager.GetString("AppBarPinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefresh {
            get {
                return ResourceManager.GetString("AppBarRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove from fav..
        /// </summary>
        public static string AppBarRemoveFromFavorites {
            get {
                return ResourceManager.GetString("AppBarRemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBarSave {
            get {
                return ResourceManager.GetString("AppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string AppBarSearch {
            get {
                return ResourceManager.GetString("AppBarSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set as home.
        /// </summary>
        public static string AppBarSetAsHome {
            get {
                return ResourceManager.GetString("AppBarSetAsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HARU.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates the live tile and sends weather alerts with the latest forecast..
        /// </summary>
        public static string BackgroundAgentDescription {
            get {
                return ResourceManager.GetString("BackgroundAgentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get weather alerts and live tile updates, turn background tasks back on in your phone&apos;s settings..
        /// </summary>
        public static string BackgroundAgentDisabledMessage {
            get {
                return ResourceManager.GetString("BackgroundAgentDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background tasks disabled.
        /// </summary>
        public static string BackgroundAgentDisabledTitle {
            get {
                return ResourceManager.GetString("BackgroundAgentDisabledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your favorite locations show up here. You can add up to {0} favorites in search..
        /// </summary>
        public static string FavoritesDescription {
            get {
                return ResourceManager.GetString("FavoritesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home · {0}.
        /// </summary>
        public static string FavoritesHomeDetail {
            get {
                return ResourceManager.GetString("FavoritesHomeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast as of {0}.
        /// </summary>
        public static string ForecastAsOf {
            get {
                return ResourceManager.GetString("ForecastAsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Japanese
        ///晴 (haru)
        ///meaning
        ///&quot;clear weather&quot;.
        /// </summary>
        public static string HaruMeaning {
            get {
                return ResourceManager.GetString("HaruMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP ICON.
        /// </summary>
        public static string LabelAppIcon {
            get {
                return ResourceManager.GetString("LabelAppIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG HUM.
        /// </summary>
        public static string LabelAvgHum {
            get {
                return ResourceManager.GetString("LabelAvgHum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITION.
        /// </summary>
        public static string LabelCondition {
            get {
                return ResourceManager.GetString("LabelCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVELOPED BY.
        /// </summary>
        public static string LabelDevelopedBy {
            get {
                return ResourceManager.GetString("LabelDevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEELS LIKE.
        /// </summary>
        public static string LabelFeelsLike {
            get {
                return ResourceManager.GetString("LabelFeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUM.
        /// </summary>
        public static string LabelHum {
            get {
                return ResourceManager.GetString("LabelHum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUMIDITY.
        /// </summary>
        public static string LabelHumidity {
            get {
                return ResourceManager.GetString("LabelHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX PREC.
        /// </summary>
        public static string LabelMaxPrec {
            get {
                return ResourceManager.GetString("LabelMaxPrec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX WIND.
        /// </summary>
        public static string LabelMaxWind {
            get {
                return ResourceManager.GetString("LabelMaxWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREC.
        /// </summary>
        public static string LabelPrec {
            get {
                return ResourceManager.GetString("LabelPrec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRECIPITATION.
        /// </summary>
        public static string LabelPrecipitation {
            get {
                return ResourceManager.GetString("LabelPrecipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESSURE.
        /// </summary>
        public static string LabelPressure {
            get {
                return ResourceManager.GetString("LabelPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMP.
        /// </summary>
        public static string LabelTemp {
            get {
                return ResourceManager.GetString("LabelTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPERATURE.
        /// </summary>
        public static string LabelTemperature {
            get {
                return ResourceManager.GetString("LabelTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEATHER FORECAST &amp; GEOCODING API.
        /// </summary>
        public static string LabelWeatherApi {
            get {
                return ResourceManager.GetString("LabelWeatherApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEATHER ICONS.
        /// </summary>
        public static string LabelWeatherIcons {
            get {
                return ResourceManager.GetString("LabelWeatherIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIND.
        /// </summary>
        public static string LabelWind {
            get {
                return ResourceManager.GetString("LabelWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIND DIRECTION.
        /// </summary>
        public static string LabelWindDirection {
            get {
                return ResourceManager.GetString("LabelWindDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIND SPEED.
        /// </summary>
        public static string LabelWindSpeed {
            get {
                return ResourceManager.GetString("LabelWindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to made with love &lt;3.
        /// </summary>
        public static string MadeWithLove {
            get {
                return ResourceManager.GetString("MadeWithLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to favorites.
        /// </summary>
        public static string MenuAddFavorite {
            get {
                return ResourceManager.GetString("MenuAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string MenuPinToStart {
            get {
                return ResourceManager.GetString("MenuPinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove from favorites.
        /// </summary>
        public static string MenuRemoveFavorite {
            get {
                return ResourceManager.GetString("MenuRemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set as home.
        /// </summary>
        public static string MenuSetAsHome {
            get {
                return ResourceManager.GetString("MenuSetAsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO LOCATION.
        /// </summary>
        public static string NoLocation {
            get {
                return ResourceManager.GetString("NoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PageAbout {
            get {
                return ResourceManager.GetString("PageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string PageFavorites {
            get {
                return ResourceManager.GetString("PageFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string PageSearch {
            get {
                return ResourceManager.GetString("PageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changelog.
        /// </summary>
        public static string PivotChangelog {
            get {
                return ResourceManager.GetString("PivotChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next 12 hours.
        /// </summary>
        public static string PivotNext12Hours {
            get {
                return ResourceManager.GetString("PivotNext12Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next 7 days.
        /// </summary>
        public static string PivotNext7Days {
            get {
                return ResourceManager.GetString("PivotNext7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right now.
        /// </summary>
        public static string PivotRightNow {
            get {
                return ResourceManager.GetString("PivotRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again later..
        /// </summary>
        public static string ProgressError {
            get {
                return ResourceManager.GetString("ProgressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching forecast....
        /// </summary>
        public static string ProgressFetchingForecast {
            get {
                return ResourceManager.GetString("ProgressFetchingForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding your location....
        /// </summary>
        public static string ProgressLocating {
            get {
                return ResourceManager.GetString("ProgressLocating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find you. Check if location is on..
        /// </summary>
        public static string ProgressLocationUnavailable {
            get {
                return ResourceManager.GetString("ProgressLocationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results for &quot;{0}&quot;.
        /// </summary>
        public static string ProgressNoResults {
            get {
                return ResourceManager.GetString("ProgressNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for &quot;{0}&quot;....
        /// </summary>
        public static string ProgressSearching {
            get {
                return ResourceManager.GetString("ProgressSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Showing last update..
        /// </summary>
        public static string ProgressShowingLastUpdate {
            get {
                return ResourceManager.GetString("ProgressShowingLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow.
        /// </summary>
        public static string PromptAllow {
            get {
                return ResourceManager.GetString("PromptAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string PromptCancel {
            get {
                return ResourceManager.GetString("PromptCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t allow.
        /// </summary>
        public static string PromptDontAllow {
            get {
                return ResourceManager.GetString("PromptDontAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t save.
        /// </summary>
        public static string PromptDontSave {
            get {
                return ResourceManager.GetString("PromptDontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only add up to {0} favorites. Remove one to add another..
        /// </summary>
        public static string PromptFavoritesFullMessage {
            get {
                return ResourceManager.GetString("PromptFavoritesFullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites are full.
        /// </summary>
        public static string PromptFavoritesFullTitle {
            get {
                return ResourceManager.GetString("PromptFavoritesFullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later.
        /// </summary>
        public static string PromptLater {
            get {
                return ResourceManager.GetString("PromptLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haru uses your phone&apos;s location to get the forecast for where you are. Your coordinates are sent to Open-Meteo to fetch the forecast and to GeoNames to look up the place name, and saved on this phone. They aren&apos;t shared with anyone else. You can turn this off at any time in settings..
        /// </summary>
        public static string PromptLocationMessage {
            get {
                return ResourceManager.GetString("PromptLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your location?.
        /// </summary>
        public static string PromptLocationTitle {
            get {
                return ResourceManager.GetString("PromptLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is your first time using Haru, you need to set a location before fetching the forecast. Do you want to set it now?.
        /// </summary>
        public static string PromptNoLocationFirstTime {
            get {
                return ResourceManager.GetString("PromptNoLocationFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to set a location before refreshing the forecast. Do you want to set it now?.
        /// </summary>
        public static string PromptNoLocationRefresh {
            get {
                return ResourceManager.GetString("PromptNoLocationRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No location set.
        /// </summary>
        public static string PromptNoLocationTitle {
            get {
                return ResourceManager.GetString("PromptNoLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okay.
        /// </summary>
        public static string PromptOkay {
            get {
                return ResourceManager.GetString("PromptOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is your home, so it goes on Haru&apos;s main tile, which apps can&apos;t pin themselves. To pin it, find Haru in the app list, tap and hold it, and tap &quot;pin to start&quot;..
        /// </summary>
        public static string PromptPinHomeMessage {
            get {
                return ResourceManager.GetString("PromptPinHomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin home to Start.
        /// </summary>
        public static string PromptPinHomeTitle {
            get {
                return ResourceManager.GetString("PromptPinHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string PromptRemove {
            get {
                return ResourceManager.GetString("PromptRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This location is pinned to Start. Removing it from favorites also unpins it..
        /// </summary>
        public static string PromptRemoveFavoriteMessage {
            get {
                return ResourceManager.GetString("PromptRemoveFavoriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorites?.
        /// </summary>
        public static string PromptRemoveFavoriteTitle {
            get {
                return ResourceManager.GetString("PromptRemoveFavoriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string PromptSave {
            get {
                return ResourceManager.GetString("PromptSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes will be lost if you don&apos;t save them..
        /// </summary>
        public static string PromptSaveChangesMessage {
            get {
                return ResourceManager.GetString("PromptSaveChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        public static string PromptSaveChangesTitle {
            get {
                return ResourceManager.GetString("PromptSaveChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string PromptYes {
            get {
                return ResourceManager.GetString("PromptYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use my location.
        /// </summary>
        public static string SearchCurrentLocation {
            get {
                return ResourceManager.GetString("SearchCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter location.
        /// </summary>
        public static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify for all favorite weather changes.
        /// </summary>
        public static string SettingAllFavoritesNotifications {
            get {
                return ResourceManager.GetString("SettingAllFavoritesNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow background updates.
        /// </summary>
        public static string SettingBackgroundUpdates {
            get {
                return ResourceManager.GetString("SettingBackgroundUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear saved forecast.
        /// </summary>
        public static string SettingClearForecast {
            get {
                return ResourceManager.GetString("SettingClearForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the previously saved forecast, making sure Haru gets the freshest and most up-to-date forecast..
        /// </summary>
        public static string SettingClearForecastDescription {
            get {
                return ResourceManager.GetString("SettingClearForecastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t clear saved forecast.
        /// </summary>
        public static string SettingClearForecastFailedTitle {
            get {
                return ResourceManager.GetString("SettingClearForecastFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fresh and up-to-date forecast will be ready the next time you refresh or open the app..
        /// </summary>
        public static string SettingClearForecastSuccessMessage {
            get {
                return ResourceManager.GetString("SettingClearForecastSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved forecast cleared!.
        /// </summary>
        public static string SettingClearForecastSuccessTitle {
            get {
                return ResourceManager.GetString("SettingClearForecastSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update live tile.
        /// </summary>
        public static string SettingLiveTile {
            get {
                return ResourceManager.GetString("SettingLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use my location.
        /// </summary>
        public static string SettingLocationService {
            get {
                return ResourceManager.GetString("SettingLocationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets Haru find your location when you tap &quot;use my location&quot; on the search page. Your coordinates are sent only to Open-Meteo to fetch the forecast and to GeoNames to look up the place name, and saved on this phone..
        /// </summary>
        public static string SettingLocationServiceDescription {
            get {
                return ResourceManager.GetString("SettingLocationServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use monochrome tile icons.
        /// </summary>
        public static string SettingMonochromeTile {
            get {
                return ResourceManager.GetString("SettingMonochromeTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify when home weather changes.
        /// </summary>
        public static string SettingNotifications {
            get {
                return ResourceManager.GetString("SettingNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation unit.
        /// </summary>
        public static string SettingPrecipitationUnit {
            get {
                return ResourceManager.GetString("SettingPrecipitationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature unit.
        /// </summary>
        public static string SettingTemperatureUnit {
            get {
                return ResourceManager.GetString("SettingTemperatureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed unit.
        /// </summary>
        public static string SettingWindSpeedUnit {
            get {
                return ResourceManager.GetString("SettingWindSpeedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius (°C).
        /// </summary>
        public static string UnitCelsius {
            get {
                return ResourceManager.GetString("UnitCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit (°F).
        /// </summary>
        public static string UnitFahrenheit {
            get {
                return ResourceManager.GetString("UnitFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches (in).
        /// </summary>
        public static string UnitInch {
            get {
                return ResourceManager.GetString("UnitInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers per hour (km/h).
        /// </summary>
        public static string UnitKmh {
            get {
                return ResourceManager.GetString("UnitKmh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knots (kn).
        /// </summary>
        public static string UnitKn {
            get {
                return ResourceManager.GetString("UnitKn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeters (mm).
        /// </summary>
        public static string UnitMm {
            get {
                return ResourceManager.GetString("UnitMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles per hour (mph).
        /// </summary>
        public static string UnitMph {
            get {
                return ResourceManager.GetString("UnitMph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters per second (m/s).
        /// </summary>
        public static string UnitMs {
            get {
                return ResourceManager.GetString("UnitMs", resourceCulture);
            }
        }
    }
}
