//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaruApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaruApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppBarCancel {
            get {
                return ResourceManager.GetString("AppBarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefresh {
            get {
                return ResourceManager.GetString("AppBarRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBarSave {
            get {
                return ResourceManager.GetString("AppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string AppBarSearch {
            get {
                return ResourceManager.GetString("AppBarSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HARU.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agents for this application have been disabled by the user..
        /// </summary>
        public static string BackgroundAgentDisabled {
            get {
                return ResourceManager.GetString("BackgroundAgentDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast as of {0}.
        /// </summary>
        public static string ForecastAsOf {
            get {
                return ResourceManager.GetString("ForecastAsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Japanese
        ///晴 (haru)
        ///meaning
        ///&quot;clear weather&quot;.
        /// </summary>
        public static string HaruMeaning {
            get {
                return ResourceManager.GetString("HaruMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP ICON.
        /// </summary>
        public static string LabelAppIcon {
            get {
                return ResourceManager.GetString("LabelAppIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG HUM.
        /// </summary>
        public static string LabelAvgHum {
            get {
                return ResourceManager.GetString("LabelAvgHum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITION.
        /// </summary>
        public static string LabelCondition {
            get {
                return ResourceManager.GetString("LabelCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVELOPED BY.
        /// </summary>
        public static string LabelDevelopedBy {
            get {
                return ResourceManager.GetString("LabelDevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEELS LIKE.
        /// </summary>
        public static string LabelFeelsLike {
            get {
                return ResourceManager.GetString("LabelFeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUM.
        /// </summary>
        public static string LabelHum {
            get {
                return ResourceManager.GetString("LabelHum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUMIDITY.
        /// </summary>
        public static string LabelHumidity {
            get {
                return ResourceManager.GetString("LabelHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX PREC.
        /// </summary>
        public static string LabelMaxPrec {
            get {
                return ResourceManager.GetString("LabelMaxPrec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX WIND.
        /// </summary>
        public static string LabelMaxWind {
            get {
                return ResourceManager.GetString("LabelMaxWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREC.
        /// </summary>
        public static string LabelPrec {
            get {
                return ResourceManager.GetString("LabelPrec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRECIPITATION.
        /// </summary>
        public static string LabelPrecipitation {
            get {
                return ResourceManager.GetString("LabelPrecipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESSURE.
        /// </summary>
        public static string LabelPressure {
            get {
                return ResourceManager.GetString("LabelPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMP.
        /// </summary>
        public static string LabelTemp {
            get {
                return ResourceManager.GetString("LabelTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPERATURE.
        /// </summary>
        public static string LabelTemperature {
            get {
                return ResourceManager.GetString("LabelTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEATHER FORECAST &amp; GEOCODING API.
        /// </summary>
        public static string LabelWeatherApi {
            get {
                return ResourceManager.GetString("LabelWeatherApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEATHER ICONS.
        /// </summary>
        public static string LabelWeatherIcons {
            get {
                return ResourceManager.GetString("LabelWeatherIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIND.
        /// </summary>
        public static string LabelWind {
            get {
                return ResourceManager.GetString("LabelWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIND DIRECTION.
        /// </summary>
        public static string LabelWindDirection {
            get {
                return ResourceManager.GetString("LabelWindDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIND SPEED.
        /// </summary>
        public static string LabelWindSpeed {
            get {
                return ResourceManager.GetString("LabelWindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to made with love &lt;3.
        /// </summary>
        public static string MadeWithLove {
            get {
                return ResourceManager.GetString("MadeWithLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO LOCATION.
        /// </summary>
        public static string NoLocation {
            get {
                return ResourceManager.GetString("NoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PageAbout {
            get {
                return ResourceManager.GetString("PageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string PageSearch {
            get {
                return ResourceManager.GetString("PageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changelog.
        /// </summary>
        public static string PivotChangelog {
            get {
                return ResourceManager.GetString("PivotChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next 12 hours.
        /// </summary>
        public static string PivotNext12Hours {
            get {
                return ResourceManager.GetString("PivotNext12Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next 7 days.
        /// </summary>
        public static string PivotNext7Days {
            get {
                return ResourceManager.GetString("PivotNext7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right now.
        /// </summary>
        public static string PivotRightNow {
            get {
                return ResourceManager.GetString("PivotRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again later..
        /// </summary>
        public static string ProgressError {
            get {
                return ResourceManager.GetString("ProgressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching forecast....
        /// </summary>
        public static string ProgressFetchingForecast {
            get {
                return ResourceManager.GetString("ProgressFetchingForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results for &quot;{0}&quot;.
        /// </summary>
        public static string ProgressNoResults {
            get {
                return ResourceManager.GetString("ProgressNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for &quot;{0}&quot;....
        /// </summary>
        public static string ProgressSearching {
            get {
                return ResourceManager.GetString("ProgressSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Showing last update..
        /// </summary>
        public static string ProgressShowingLastUpdate {
            get {
                return ResourceManager.GetString("ProgressShowingLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t save.
        /// </summary>
        public static string PromptDontSave {
            get {
                return ResourceManager.GetString("PromptDontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later.
        /// </summary>
        public static string PromptLater {
            get {
                return ResourceManager.GetString("PromptLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is your first time using Haru, you need to set a location before fetching the forecast. Do you want to set it now?.
        /// </summary>
        public static string PromptNoLocationFirstTime {
            get {
                return ResourceManager.GetString("PromptNoLocationFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to set a location before refreshing the forecast. Do you want to set it now?.
        /// </summary>
        public static string PromptNoLocationRefresh {
            get {
                return ResourceManager.GetString("PromptNoLocationRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No location set.
        /// </summary>
        public static string PromptNoLocationTitle {
            get {
                return ResourceManager.GetString("PromptNoLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okay.
        /// </summary>
        public static string PromptOkay {
            get {
                return ResourceManager.GetString("PromptOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string PromptSave {
            get {
                return ResourceManager.GetString("PromptSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes will be lost if you don&apos;t save them..
        /// </summary>
        public static string PromptSaveChangesMessage {
            get {
                return ResourceManager.GetString("PromptSaveChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        public static string PromptSaveChangesTitle {
            get {
                return ResourceManager.GetString("PromptSaveChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string PromptYes {
            get {
                return ResourceManager.GetString("PromptYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter location.
        /// </summary>
        public static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow background updates.
        /// </summary>
        public static string SettingBackgroundUpdates {
            get {
                return ResourceManager.GetString("SettingBackgroundUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear saved forecast.
        /// </summary>
        public static string SettingClearForecast {
            get {
                return ResourceManager.GetString("SettingClearForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the previously saved forecast, making sure Haru gets the freshest and most up-to-date forecast..
        /// </summary>
        public static string SettingClearForecastDescription {
            get {
                return ResourceManager.GetString("SettingClearForecastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fresh and up-to-date forecast will be ready the next time you refresh or open the app..
        /// </summary>
        public static string SettingClearForecastSuccessMessage {
            get {
                return ResourceManager.GetString("SettingClearForecastSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved forecast cleared!.
        /// </summary>
        public static string SettingClearForecastSuccessTitle {
            get {
                return ResourceManager.GetString("SettingClearForecastSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use monochrome tile icons.
        /// </summary>
        public static string SettingMonochromeTile {
            get {
                return ResourceManager.GetString("SettingMonochromeTile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update live tile.
        /// </summary>
        public static string SettingLiveTile {
            get {
                return ResourceManager.GetString("SettingLiveTile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notify on weather changes.
        /// </summary>
        public static string SettingNotifications {
            get {
                return ResourceManager.GetString("SettingNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation unit.
        /// </summary>
        public static string SettingPrecipitationUnit {
            get {
                return ResourceManager.GetString("SettingPrecipitationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature unit.
        /// </summary>
        public static string SettingTemperatureUnit {
            get {
                return ResourceManager.GetString("SettingTemperatureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed unit.
        /// </summary>
        public static string SettingWindSpeedUnit {
            get {
                return ResourceManager.GetString("SettingWindSpeedUnit", resourceCulture);
            }
        }
    }
}
