using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HaruCore
{
    public class WeatherInterpretationModel
    {
        private static readonly Dictionary<int, string> WeatherDescriptions = new Dictionary<int, string>
        {
            { 0, "clear" },
            { 1, "mostly clear" },
            { 2, "partly cloudy" },
            { 3, "cloudy" },
            { 4, "smoke" },
            { 5, "haze" },
            { 6, "some dust" },
            { 7, "dust" },
            { 8, "dust / sand whirls" },
            { 9, "duststorms / sandstorms" },
            { 10, "mist" },
            { 11, "foggy patches" },
            { 12, "foggy" },
            { 13, "distant lightning" },
            { 14, "distant drizzle" },
            { 15, "distant rain" },
            { 16, "rain within sight" },
            { 17, "thunder" },
            { 18, "squalls" },
            { 19, "funnel clouds" },
            { 20, "drizzle (previous hour)" },
            { 21, "light rain (previous hour)" },
            { 22, "light snow (previous hour)" },
            { 23, "sleet / snow / hail (previous hour)" },
            { 24, "freezing drizzle / rain (previous hour)" },
            { 25, "rain (previous hour)" },
            { 26, "snow (previous hour)" },
            { 27, "hail (previous hour)" },
            { 28, "fog (previous hour)" },
            { 29, "thunderstorm (previous hour)" },
            { 30, "slight duststorm (receding)" },
            { 31, "slight duststorm (ongoing)" },
            { 32, "duststorm (building up)" },
            { 33, "duststorm (receding)" },
            { 34, "duststorm (ongoing)" },
            { 35, "severe duststorm (building up)" },
            { 36, "slight drifting snow" },
            { 37, "heavy drifting snow" },
            { 38, "slight blowing snow" },
            { 39, "heavy blowing snow" },
            { 40, "distant fog" },
            { 41, "fog patches" },
            { 42, "low fog (receding)" },
            { 43, "fog (receding)" },
            { 44, "low fog (ongoing)" },
            { 45, "fog (ongoing)" },
            { 46, "low fog (building up)" },
            { 47, "fog (building up)" },
            { 48, "low freezing fog" },
            { 49, "freezing fog" },
            { 50, "light intermittent drizzle" },
            { 51, "light drizzle" },
            { 52, "intermittent drizzle" },
            { 53, "drizzle" },
            { 54, "dense intermittent drizzle" },
            { 55, "dense drizzle" },
            { 56, "slight freezing drizzle" },
            { 57, "freezing drizzle" },
            { 58, "light rain / drizzle" },
            { 59, "rain / drizzle" },
            { 60, "light intermittent rain" },
            { 61, "light rain" },
            { 62, "intermittent rain" },
            { 63, "rain" },
            { 64, "heavy intermittent rain" },
            { 65, "heavy rain" },
            { 66, "slight freezing rain" },
            { 67, "freezing rain" },
            { 68, "light sleet" },
            { 69, "sleet" },
            { 70, "light intermittent snowfalls" },
            { 71, "light snowfall" },
            { 72, "intermittent snowfalls" },
            { 73, "snowfall" },
            { 74, "heavy intermittent snowfalls" },
            { 75, "heavy snowfall" },
            { 76, "diamond dust" },
            { 77, "snow grains" },
            { 78, "sparse snow crystals" },
            { 79, "ice pellets" },
            { 80, "light rain showers" },
            { 81, "rain showers" },
            { 82, "very heavy rain showers" },
            { 83, "light sleet showers" },
            { 84, "sleet showers" },
            { 85, "light snow showers" },
            { 86, "snow showers" },
            { 87, "light snow pellets / small hail" },
            { 88, "snow pellets / small hail" },
            { 89, "slight hail showers" },
            { 90, "hail showers" },
            { 91, "light rain (post-thunderstorm)" },
            { 92, "rain (post-thunderstorm)" },
            { 93, "light snow (post-thunderstorm)" },
            { 94, "snow (post-thunderstorm)" },
            { 95, "thunderstorm with showers" },
            { 96, "thunderstorm with hail" },
            { 97, "heavy thunderstorm with showers" },
            { 98, "thunderstorm with dust/sandstorm" },
            { 99, "heavy thunderstorm with hail" }
        };

        private static readonly Dictionary<int, string> WeatherIcons = new Dictionary<int, string>
        {
            { 0, "/Assets/WeatherIcons/clear-day.png" },
            { 1, "/Assets/WeatherIcons/cloudy.png" },
            { 2, "/Assets/WeatherIcons/overcast.png" },
            { 3, "/Assets/WeatherIcons/cloudy.png" },
            { 4, "/Assets/WeatherIcons/smoke.png" },
            { 5, "/Assets/WeatherIcons/haze.png" },
            { 6, "/Assets/WeatherIcons/dust.png" },
            { 7, "/Assets/WeatherIcons/dust.png" },
            { 8, "/Assets/WeatherIcons/dust-wind.png" },
            { 9, "/Assets/WeatherIcons/dust-wind.png" },
            { 10, "/Assets/WeatherIcons/mist.png" },
            { 11, "/Assets/WeatherIcons/fog.png" },
            { 12, "/Assets/WeatherIcons/fog.png" },
            { 13, "/Assets/WeatherIcons/thunderstorms.png" },
            { 14, "/Assets/WeatherIcons/drizzle.png" },
            { 15, "/Assets/WeatherIcons/drizzle.png" },
            { 16, "/Assets/WeatherIcons/drizzle.png" },
            { 17, "/Assets/WeatherIcons/thunderstorms.png" },
            { 18, "/Assets/WeatherIcons/wind.png" },
            { 19, "/Assets/WeatherIcons/tornado.png" },
            { 20, "/Assets/WeatherIcons/drizzle.png" },
            { 21, "/Assets/WeatherIcons/drizzle.png" },
            { 22, "/Assets/WeatherIcons/snow.png" },
            { 23, "/Assets/WeatherIcons/sleet.png" },
            { 24, "/Assets/WeatherIcons/sleet.png" },
            { 25, "/Assets/WeatherIcons/drizzle.png" },
            { 26, "/Assets/WeatherIcons/snow.png" },
            { 27, "/Assets/WeatherIcons/hail.png" },
            { 28, "/Assets/WeatherIcons/fog.png" },
            { 29, "/Assets/WeatherIcons/thunderstorms.png" },
            { 30, "/Assets/WeatherIcons/dust.png" },
            { 31, "/Assets/WeatherIcons/dust.png" },
            { 32, "/Assets/WeatherIcons/dust-wind.png" },
            { 33, "/Assets/WeatherIcons/dust.png" },
            { 34, "/Assets/WeatherIcons/dust-wind.png" },
            { 35, "/Assets/WeatherIcons/dust-wind.png" },
            { 36, "/Assets/WeatherIcons/wind.png" },
            { 37, "/Assets/WeatherIcons/wind.png" },
            { 38, "/Assets/WeatherIcons/wind.png" },
            { 39, "/Assets/WeatherIcons/wind.png" },
            { 40, "/Assets/WeatherIcons/fog.png" },
            { 41, "/Assets/WeatherIcons/fog.png" },
            { 42, "/Assets/WeatherIcons/fog.png" },
            { 43, "/Assets/WeatherIcons/fog.png" },
            { 44, "/Assets/WeatherIcons/fog.png" },
            { 45, "/Assets/WeatherIcons/fog.png" },
            { 46, "/Assets/WeatherIcons/fog.png" },
            { 47, "/Assets/WeatherIcons/fog.png" },
            { 48, "/Assets/WeatherIcons/fog.png" },
            { 49, "/Assets/WeatherIcons/fog.png" },
            { 50, "/Assets/WeatherIcons/drizzle.png" },
            { 51, "/Assets/WeatherIcons/drizzle.png" },
            { 52, "/Assets/WeatherIcons/drizzle.png" },
            { 53, "/Assets/WeatherIcons/drizzle.png" },
            { 54, "/Assets/WeatherIcons/drizzle.png" },
            { 55, "/Assets/WeatherIcons/drizzle.png" },
            { 56, "/Assets/WeatherIcons/sleet.png" },
            { 57, "/Assets/WeatherIcons/sleet.png" },
            { 58, "/Assets/WeatherIcons/drizzle.png" },
            { 59, "/Assets/WeatherIcons/drizzle.png" },
            { 60, "/Assets/WeatherIcons/rain.png" },
            { 61, "/Assets/WeatherIcons/drizzle.png" },
            { 62, "/Assets/WeatherIcons/drizzle.png" },
            { 63, "/Assets/WeatherIcons/rain.png" },
            { 64, "/Assets/WeatherIcons/rain.png" },
            { 65, "/Assets/WeatherIcons/rain.png" },
            { 66, "/Assets/WeatherIcons/sleet.png" },
            { 67, "/Assets/WeatherIcons/sleet.png" },
            { 68, "/Assets/WeatherIcons/sleet.png" },
            { 69, "/Assets/WeatherIcons/sleet.png" },
            { 70, "/Assets/WeatherIcons/snow.png" },
            { 71, "/Assets/WeatherIcons/snow.png" },
            { 72, "/Assets/WeatherIcons/snow.png" },
            { 73, "/Assets/WeatherIcons/snow.png" },
            { 74, "/Assets/WeatherIcons/snow.png" },
            { 75, "/Assets/WeatherIcons/snow.png" },
            { 76, "/Assets/WeatherIcons/snow.png" },
            { 77, "/Assets/WeatherIcons/hail.png" },
            { 78, "/Assets/WeatherIcons/snow.png" },
            { 79, "/Assets/WeatherIcons/hail.png" },
            { 80, "/Assets/WeatherIcons/drizzle.png" },
            { 81, "/Assets/WeatherIcons/rain.png" },
            { 82, "/Assets/WeatherIcons/rain.png" },
            { 83, "/Assets/WeatherIcons/sleet.png" },
            { 84, "/Assets/WeatherIcons/sleet.png" },
            { 85, "/Assets/WeatherIcons/snow.png" },
            { 86, "/Assets/WeatherIcons/snow.png" },
            { 87, "/Assets/WeatherIcons/hail.png" },
            { 88, "/Assets/WeatherIcons/hail.png" },
            { 89, "/Assets/WeatherIcons/hail.png" },
            { 90, "/Assets/WeatherIcons/hail.png" },
            { 91, "/Assets/WeatherIcons/drizzle.png" },
            { 92, "/Assets/WeatherIcons/rain.png" },
            { 93, "/Assets/WeatherIcons/snow.png" },
            { 94, "/Assets/WeatherIcons/snow.png" },
            { 95, "/Assets/WeatherIcons/thunderstorms-rain.png" },
            { 96, "/Assets/WeatherIcons/thunderstorms-rain.png" },
            { 97, "/Assets/WeatherIcons/thunderstorms-rain.png" },
            { 98, "/Assets/WeatherIcons/thunderstorms.png" },
            { 99, "/Assets/WeatherIcons/thunderstorms-rain.png" },
        };        

        private static readonly Dictionary<int, string> WeatherIconsDay = new Dictionary<int, string>
        {
            { 0, "/Assets/WeatherIcons/clear-day.png" },
            { 1, "/Assets/WeatherIcons/partly-cloudy-day.png" },
            { 2, "/Assets/WeatherIcons/overcast-day.png" },
            { 3, "/Assets/WeatherIcons/cloudy.png" },
            { 4, "/Assets/WeatherIcons/smoke.png" },
            { 5, "/Assets/WeatherIcons/haze-day.png" },
            { 6, "/Assets/WeatherIcons/dust-day.png" },
            { 7, "/Assets/WeatherIcons/dust.png" },
            { 8, "/Assets/WeatherIcons/dust-wind.png" },
            { 9, "/Assets/WeatherIcons/dust-wind.png" },
            { 10, "/Assets/WeatherIcons/mist.png" },
            { 11, "/Assets/WeatherIcons/fog-day.png" },
            { 12, "/Assets/WeatherIcons/fog.png" },
            { 13, "/Assets/WeatherIcons/thunderstorms-day.png" },
            { 14, "/Assets/WeatherIcons/partly-cloudy-day-drizzle.png" },
            { 15, "/Assets/WeatherIcons/partly-cloudy-day-drizzle.png" },
            { 16, "/Assets/WeatherIcons/partly-cloudy-day-drizzle.png" },
            { 17, "/Assets/WeatherIcons/thunderstorms-day.png" },
            { 18, "/Assets/WeatherIcons/wind.png" },
            { 19, "/Assets/WeatherIcons/tornado.png" },
            { 20, "/Assets/WeatherIcons/partly-cloudy-day-drizzle.png" },
            { 21, "/Assets/WeatherIcons/partly-cloudy-day-drizzle.png" },
            { 22, "/Assets/WeatherIcons/partly-cloudy-day-snow.png" },
            { 23, "/Assets/WeatherIcons/partly-cloudy-day-sleet.png" },
            { 24, "/Assets/WeatherIcons/partly-cloudy-day-sleet.png" },
            { 25, "/Assets/WeatherIcons/partly-cloudy-day-drizzle.png" },
            { 26, "/Assets/WeatherIcons/partly-cloudy-day-snow.png" },
            { 27, "/Assets/WeatherIcons/partly-cloudy-day-hail.png" },
            { 28, "/Assets/WeatherIcons/fog-day.png" },
            { 29, "/Assets/WeatherIcons/thunderstorms-day.png" },
            { 30, "/Assets/WeatherIcons/dust-day.png" },
            { 31, "/Assets/WeatherIcons/dust-day.png" },
            { 32, "/Assets/WeatherIcons/dust-wind.png" },
            { 33, "/Assets/WeatherIcons/dust-day.png" },
            { 34, "/Assets/WeatherIcons/dust-wind.png" },
            { 35, "/Assets/WeatherIcons/dust-wind.png" },
            { 36, "/Assets/WeatherIcons/wind.png" },
            { 37, "/Assets/WeatherIcons/wind.png" },
            { 38, "/Assets/WeatherIcons/wind.png" },
            { 39, "/Assets/WeatherIcons/wind.png" },
            { 40, "/Assets/WeatherIcons/partly-cloudy-day-fog.png" },
            { 41, "/Assets/WeatherIcons/fog-day.png" },
            { 42, "/Assets/WeatherIcons/fog-day.png" },
            { 43, "/Assets/WeatherIcons/partly-cloudy-day-fog.png" },
            { 44, "/Assets/WeatherIcons/partly-cloudy-day-fog.png" },
            { 45, "/Assets/WeatherIcons/fog.png" },
            { 46, "/Assets/WeatherIcons/partly-cloudy-day-fog.png" },
            { 47, "/Assets/WeatherIcons/fog.png" },
            { 48, "/Assets/WeatherIcons/partly-cloudy-day-fog.png" },
            { 49, "/Assets/WeatherIcons/fog.png" },
            { 50, "/Assets/WeatherIcons/partly-cloudy-day-drizzle.png" },
            { 51, "/Assets/WeatherIcons/drizzle.png" },
            { 52, "/Assets/WeatherIcons/drizzle.png" },
            { 53, "/Assets/WeatherIcons/drizzle.png" },
            { 54, "/Assets/WeatherIcons/drizzle.png" },
            { 55, "/Assets/WeatherIcons/drizzle.png" },
            { 56, "/Assets/WeatherIcons/sleet.png" },
            { 57, "/Assets/WeatherIcons/sleet.png" },
            { 58, "/Assets/WeatherIcons/drizzle.png" },
            { 59, "/Assets/WeatherIcons/drizzle.png" },
            { 60, "/Assets/WeatherIcons/partly-cloudy-day-rain.png" },
            { 61, "/Assets/WeatherIcons/drizzle.png" },
            { 62, "/Assets/WeatherIcons/drizzle.png" },
            { 63, "/Assets/WeatherIcons/rain.png" },
            { 64, "/Assets/WeatherIcons/rain.png" },
            { 65, "/Assets/WeatherIcons/rain.png" },
            { 66, "/Assets/WeatherIcons/sleet.png" },
            { 67, "/Assets/WeatherIcons/sleet.png" },
            { 68, "/Assets/WeatherIcons/sleet.png" },
            { 69, "/Assets/WeatherIcons/sleet.png" },
            { 70, "/Assets/WeatherIcons/partly-cloudy-day-snow.png" },
            { 71, "/Assets/WeatherIcons/snow.png" },
            { 72, "/Assets/WeatherIcons/snow.png" },
            { 73, "/Assets/WeatherIcons/snow.png" },
            { 74, "/Assets/WeatherIcons/snow.png" },
            { 75, "/Assets/WeatherIcons/snow.png" },
            { 76, "/Assets/WeatherIcons/snow.png" },
            { 77, "/Assets/WeatherIcons/hail.png" },
            { 78, "/Assets/WeatherIcons/snow.png" },
            { 79, "/Assets/WeatherIcons/hail.png" },
            { 80, "/Assets/WeatherIcons/drizzle.png" },
            { 81, "/Assets/WeatherIcons/rain.png" },
            { 82, "/Assets/WeatherIcons/rain.png" },
            { 83, "/Assets/WeatherIcons/sleet.png" },
            { 84, "/Assets/WeatherIcons/sleet.png" },
            { 85, "/Assets/WeatherIcons/snow.png" },
            { 86, "/Assets/WeatherIcons/snow.png" },
            { 87, "/Assets/WeatherIcons/hail.png" },
            { 88, "/Assets/WeatherIcons/hail.png" },
            { 89, "/Assets/WeatherIcons/hail.png" },
            { 90, "/Assets/WeatherIcons/hail.png" },
            { 91, "/Assets/WeatherIcons/drizzle.png" },
            { 92, "/Assets/WeatherIcons/rain.png" },
            { 93, "/Assets/WeatherIcons/snow.png" },
            { 94, "/Assets/WeatherIcons/snow.png" },
            { 95, "/Assets/WeatherIcons/thunderstorms-rain.png" },
            { 96, "/Assets/WeatherIcons/thunderstorms-rain.png" },
            { 97, "/Assets/WeatherIcons/thunderstorms-rain.png" },
            { 98, "/Assets/WeatherIcons/thunderstorms.png" },
            { 99, "/Assets/WeatherIcons/thunderstorms-rain.png" },
        };

        private static readonly Dictionary<int, string> WeatherIconsNight = new Dictionary<int, string>
        {
            { 0, "/Assets/WeatherIcons/clear-night.png" },
            { 1, "/Assets/WeatherIcons/partly-cloudy-night.png" },
            { 2, "/Assets/WeatherIcons/overcast-night.png" },
            { 3, "/Assets/WeatherIcons/cloudy.png" },
            { 4, "/Assets/WeatherIcons/smoke.png" },
            { 5, "/Assets/WeatherIcons/haze-night.png" },
            { 6, "/Assets/WeatherIcons/dust-night.png" },
            { 7, "/Assets/WeatherIcons/dust.png" },
            { 8, "/Assets/WeatherIcons/dust-wind.png" },
            { 9, "/Assets/WeatherIcons/dust-wind.png" },
            { 10, "/Assets/WeatherIcons/mist.png" },
            { 11, "/Assets/WeatherIcons/fog-night.png" },
            { 12, "/Assets/WeatherIcons/fog.png" },
            { 13, "/Assets/WeatherIcons/thunderstorms-night.png" },
            { 14, "/Assets/WeatherIcons/partly-cloudy-night-drizzle.png" },
            { 15, "/Assets/WeatherIcons/partly-cloudy-night-drizzle.png" },
            { 16, "/Assets/WeatherIcons/partly-cloudy-night-drizzle.png" },
            { 17, "/Assets/WeatherIcons/thunderstorms-night.png" },
            { 18, "/Assets/WeatherIcons/wind.png" },
            { 19, "/Assets/WeatherIcons/tornado.png" },
            { 20, "/Assets/WeatherIcons/partly-cloudy-night-drizzle.png" },
            { 21, "/Assets/WeatherIcons/partly-cloudy-night-drizzle.png" },
            { 22, "/Assets/WeatherIcons/partly-cloudy-night-snow.png" },
            { 23, "/Assets/WeatherIcons/partly-cloudy-night-sleet.png" },
            { 24, "/Assets/WeatherIcons/partly-cloudy-night-sleet.png" },
            { 25, "/Assets/WeatherIcons/partly-cloudy-night-drizzle.png" },
            { 26, "/Assets/WeatherIcons/partly-cloudy-night-snow.png" },
            { 27, "/Assets/WeatherIcons/partly-cloudy-night-hail.png" },
            { 28, "/Assets/WeatherIcons/fog-night.png" },
            { 29, "/Assets/WeatherIcons/thunderstorms-night.png" },
            { 30, "/Assets/WeatherIcons/dust-night.png" },
            { 31, "/Assets/WeatherIcons/dust-night.png" },
            { 32, "/Assets/WeatherIcons/dust-wind.png" },
            { 33, "/Assets/WeatherIcons/dust-night.png" },
            { 34, "/Assets/WeatherIcons/dust-wind.png" },
            { 35, "/Assets/WeatherIcons/dust-wind.png" },
            { 36, "/Assets/WeatherIcons/wind.png" },
            { 37, "/Assets/WeatherIcons/wind.png" },
            { 38, "/Assets/WeatherIcons/wind.png" },
            { 39, "/Assets/WeatherIcons/wind.png" },
            { 40, "/Assets/WeatherIcons/partly-cloudy-night-fog.png" },
            { 41, "/Assets/WeatherIcons/fog-night.png" },
            { 42, "/Assets/WeatherIcons/fog-night.png" },
            { 43, "/Assets/WeatherIcons/partly-cloudy-night-fog.png" },
            { 44, "/Assets/WeatherIcons/partly-cloudy-night-fog.png" },
            { 45, "/Assets/WeatherIcons/fog.png" },
            { 46, "/Assets/WeatherIcons/partly-cloudy-night-fog.png" },
            { 47, "/Assets/WeatherIcons/fog.png" },
            { 48, "/Assets/WeatherIcons/partly-cloudy-night-fog.png" },
            { 49, "/Assets/WeatherIcons/fog.png" },
            { 50, "/Assets/WeatherIcons/partly-cloudy-night-drizzle.png" },
            { 51, "/Assets/WeatherIcons/drizzle.png" },
            { 52, "/Assets/WeatherIcons/drizzle.png" },
            { 53, "/Assets/WeatherIcons/drizzle.png" },
            { 54, "/Assets/WeatherIcons/drizzle.png" },
            { 55, "/Assets/WeatherIcons/drizzle.png" },
            { 56, "/Assets/WeatherIcons/sleet.png" },
            { 57, "/Assets/WeatherIcons/sleet.png" },
            { 58, "/Assets/WeatherIcons/drizzle.png" },
            { 59, "/Assets/WeatherIcons/drizzle.png" },
            { 60, "/Assets/WeatherIcons/partly-cloudy-night-rain.png" },
            { 61, "/Assets/WeatherIcons/drizzle.png" },
            { 62, "/Assets/WeatherIcons/drizzle.png" },
            { 63, "/Assets/WeatherIcons/rain.png" },
            { 64, "/Assets/WeatherIcons/rain.png" },
            { 65, "/Assets/WeatherIcons/rain.png" },
            { 66, "/Assets/WeatherIcons/sleet.png" },
            { 67, "/Assets/WeatherIcons/sleet.png" },
            { 68, "/Assets/WeatherIcons/sleet.png" },
            { 69, "/Assets/WeatherIcons/sleet.png" },
            { 70, "/Assets/WeatherIcons/partly-cloudy-night-snow.png" },
            { 71, "/Assets/WeatherIcons/snow.png" },
            { 72, "/Assets/WeatherIcons/snow.png" },
            { 73, "/Assets/WeatherIcons/snow.png" },
            { 74, "/Assets/WeatherIcons/snow.png" },
            { 75, "/Assets/WeatherIcons/snow.png" },
            { 76, "/Assets/WeatherIcons/snow.png" },
            { 77, "/Assets/WeatherIcons/hail.png" },
            { 78, "/Assets/WeatherIcons/snow.png" },
            { 79, "/Assets/WeatherIcons/hail.png" },
            { 80, "/Assets/WeatherIcons/drizzle.png" },
            { 81, "/Assets/WeatherIcons/rain.png" },
            { 82, "/Assets/WeatherIcons/rain.png" },
            { 83, "/Assets/WeatherIcons/sleet.png" },
            { 84, "/Assets/WeatherIcons/sleet.png" },
            { 85, "/Assets/WeatherIcons/snow.png" },
            { 86, "/Assets/WeatherIcons/snow.png" },
            { 87, "/Assets/WeatherIcons/hail.png" },
            { 88, "/Assets/WeatherIcons/hail.png" },
            { 89, "/Assets/WeatherIcons/hail.png" },
            { 90, "/Assets/WeatherIcons/hail.png" },
            { 91, "/Assets/WeatherIcons/drizzle.png" },
            { 92, "/Assets/WeatherIcons/rain.png" },
            { 93, "/Assets/WeatherIcons/snow.png" },
            { 94, "/Assets/WeatherIcons/snow.png" },
            { 95, "/Assets/WeatherIcons/thunderstorms-rain.png" },
            { 96, "/Assets/WeatherIcons/thunderstorms-rain.png" },
            { 97, "/Assets/WeatherIcons/thunderstorms-rain.png" },
            { 98, "/Assets/WeatherIcons/thunderstorms.png" },
            { 99, "/Assets/WeatherIcons/thunderstorms-rain.png" }
        };

        public static string GetWeatherDescription(int weatherCode)
        {
            string description;
            if (WeatherDescriptions.TryGetValue(weatherCode, out description))
                return description;

            return "unknown";
        }

        public static string GetWeatherDescription(int weatherCode, bool isDay)
        {
            if (weatherCode == 0) return isDay ? "sunny" : "clear";
            if (weatherCode == 1) return isDay ? "mostly sunny" : "mostly clear";

            string description;
            if (WeatherDescriptions.TryGetValue(weatherCode, out description))
                return description;

            return "unknown";
        }

        public static string GetWeatherIcon(int weatherCode)
        {
            Dictionary<int, string> icons = WeatherIcons;
            string iconPath;
            if (icons.TryGetValue(weatherCode, out iconPath))
                return iconPath;

            return "/Assets/WeatherIcons/not-available.png";
        }

        public static string GetWeatherIcon(int weatherCode, bool isDay)
        {
            Dictionary<int, string> icons = isDay ? WeatherIconsDay : WeatherIconsNight;
            string iconPath;
            if (icons.TryGetValue(weatherCode, out iconPath))
                return iconPath;

            return "/Assets/WeatherIcons/not-available.png";
        }
    }
}